name: build-draft-release

on:
  workflow_dispatch: # запуск вручную из вкладки Actions

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute version
        id: v
        run: |
          # Если запуск с уже созданным тегом — используем его
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
          else
            # Если тега нет — берём версию руками (можно указать при запуске как input)
            echo "version=0.1.0" >> $GITHUB_OUTPUT
          fi

      - name: Prepare zip
        run: |
          mkdir -p dist
          if [ -d GuildRecruiter ]; then
            zip -r "dist/GuildRecruiter-${{ steps.v.outputs.version }}.zip" GuildRecruiter -x "*/.git/*"
          else
            mkdir -p pkg/GuildRecruiter
            cp -f *.toc *.lua pkg/GuildRecruiter/ 2>/dev/null || true
            (cd pkg && zip -r "../dist/GuildRecruiter-${{ steps.v.outputs.version }}.zip" GuildRecruiter)
          fi
          echo "Built archive:"
          ls -lh dist/

      - name: Create or update draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.v.outputs.version }}
          name: GuildRecruiter v${{ steps.v.outputs.version }}
          draft: true
          prerelease: false
          files: |
            dist/GuildRecruiter-${{ steps.v.outputs.version }}.zip
