name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # нужно 0, чтобы git log и describe работали корректно

      - name: Compute version
        id: v
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Debug listing
        run: |
          echo "Root:"
          ls -la
          if [ -d GuildRecruiter ]; then
            echo "GuildRecruiter/:"
            ls -la GuildRecruiter
          else
            echo "No GuildRecruiter/ dir"
          fi

      - name: Prepare zip
        run: |
          set -e
          mkdir -p dist
          if [ -d GuildRecruiter ]; then
            echo "Packing existing GuildRecruiter/ directory"
            zip -r "dist/GuildRecruiter-v${{ steps.v.outputs.version }}.zip" GuildRecruiter -x "*/.git/*"
          else
            echo "GuildRecruiter/ not found, creating package from root files"
            mkdir -p pkg/GuildRecruiter
            cp -f *.toc *.lua pkg/GuildRecruiter/ 2>/dev/null || true
            if ! ls pkg/GuildRecruiter/*.toc >/dev/null 2>&1; then
              echo "No TOC found to package. Abort."
              exit 12
            fi
            (cd pkg && zip -r "../dist/GuildRecruiter-v${{ steps.v.outputs.version }}.zip" GuildRecruiter)
          fi
          echo "Built archive:"
          ls -lh dist/

      - name: Get previous tag
        id: prevtag
        run: |
          prev_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          echo "previous_tag=$prev_tag" >> $GITHUB_OUTPUT
          echo "Previous tag: $prev_tag"

      - name: Generate release notes
        id: notes
        uses: actions/github-script@v7
        env:
          PREV_TAG: ${{ steps.prevtag.outputs.previous_tag }}
        with:
          script: |
            const core = require('@actions/core');
            const tag = context.ref.replace('refs/tags/', '');
            const prevTag = process.env.PREV_TAG || undefined;
            try {
              const params = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: tag,
                target_commitish: process.env.GITHUB_SHA
              };
              if (prevTag) {
                params.previous_tag_name = prevTag;
                core.info(`Using previous_tag_name: ${prevTag}`);
              } else {
                core.warning('Previous tag not found — letting GitHub auto-detect range');
              }
              const { data } = await github.rest.repos.generateReleaseNotes(params);
              const body = (data && data.body && data.body.trim())
                ? data.body
                : `### Changes\n- ${tag} released.`;
              core.info(`Generated notes (preview): ${body.slice(0, 200).replace(/\\n/g, ' ')}`);
              return body;
            } catch (e) {
              core.warning(`generateReleaseNotes failed: ${e.message}`);
              const fallback = `### Changes\n- ${tag} released.`;
              core.info(`Using fallback notes: ${fallback}`);
              return fallback;
            }

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: GuildRecruiter ${{ github.ref_name }}
          body: ${{ steps.notes.outputs.result }}
          draft: false
          prerelease: false
          generate_release_notes: false
          files: |
            dist/GuildRecruiter-v${{ steps.v.outputs.version }}.zip
